# Generated by Django 5.2.6 on 2025-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField()),
                ('st_name', models.CharField(max_length=70)),
                ('st_l_name', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
